spring:
  datasource:
    url: jdbc:mysql://localhost:3306/birthday_wisher
    password: Larry123
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  mail:
    username: ezeifeanyi2026@gmail.com
    password: jpgr ylfh qpqw gmzk
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          socketFactory:
            port: 465
            class : javax.net.ssl.SSLSocketFactory
          auth: true
#          connectiontimeout: 5000
#          timeout: 5000
#          writetimeout: 5000
        starttls:
          enabled: true
#    transport:
#      protocol: smtp

server:
  port: 6097
  servlet:
    context-path: /birthdaywisher/